### ISSUE TITLE
in v5.2 why remove all the Var Values list ? 

### ISSUE THREAD

**Issue by raykai** [Inforcer25/Rust-Server-Manager#1]
just wondering why the Advanced Var value default list was removed (now called custom server variables) ... its a pain to add em all back and was way better having a starting list of advance option we can change

**Comment by AdriaanBoshoff** [comment]
Sorry about that but a lot of people were annoyed by them so I made it that you can manually add them. You can find a list of variables here: https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server or you can just use the find command in the console. To list all variables use find * and to list one thing like radiation you can use find radiation and it will show you everything related to it.
